version: "3.9"

services:
  human_parser:
    build: .
    container_name: human_parser
    ports:
      - "8000:8000" 
    volumes:
      - ./jobs:/tmp/jobs 
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped
